### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Wget#1]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by deqenq** [comment]
@gep13 Hello, thank you for your message. I agree to move the addin to the `cake-contrib`. I have already added `cake-contrib` to the nuget package owners (current status is `pending approval` as of time of writing this). I read this [document](https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation) and I am not sure what should be the next step? Is it transfer the repository to a member of the Cake Team?

**Comment by gep13** [comment]
@deqenq that is great news, thank you very much!

In terms of transferring the repository to the cake-contrib Organisation on GitHub, the process starts by transferring the repository to my individual account (**gep13**), and from there, I would transfer it through to the Organisation.  Would you like to start that process?

Regarding the NuGet package, I have not seen any email about becoming a co-owner of the package.  Can I ask that you cancel the current request, and try again?

Thanks

**Comment by deqenq** [comment]
@gep13 I added `cake-contrib` to owner of nuget package again, hope that it will work now. Also I transferred this repository to you.

**Comment by gep13** [comment]
@deqenq thank you, this all seems to have worked this time, not sure what happened last time.  I got an email to say that the request was being cancelled, but the original email never made it.  Anyway, all sorted!

cake-contrib user is now added to the NuGet package:

https://www.nuget.org/packages/Cake.Wget/

Repository has been moved to cake-contrib Organisation:

https://github.com/cake-contrib/Cake.Wget

I have invited you to join the Organisation, with full admin permissions on this repository, and I am currently running a synchronisation script between GitHub and AppVeyor, to give you all the required permissions on the new AppVeyor project that I have just created for running the CI/CD builds from this repository.

If you have/use them, can you let me know what you Twitter username is, and also what the best email would be to use to invite you to a Slack Team for Cake-Contrib Maintainers.

Please let me know if you have any questions about anything.

**Comment by deqenq** [comment]
@gep13 Thank you for your effort! I do not use Twitter (or other, also be called social networks, sorry to be asocial), if it is mandatory I can create some Twitter account. The best email to contact me is `deqenq@gmail.com` which I monitor on daily basis.

**Comment by gep13** [comment]
>@deqenq said...
if it is mandatory I can create some Twitter account

No, certainly not mandatory.  I would have followed your Twitter account from the cake-contrib Twitter account, that is all.  It is really a mechanism for people to get some insight to who is involved in the Cake-Contrib Organisation, so there is no hard requirement to have one, more of a "nice to have".

I have sent you an invite to join the Cake-Contrib Slack Team.
