### ISSUE TITLE
ArgumentCustomization doesn't exists 

### ISSUE THREAD

**Issue by badrshs** [cake-contrib/Cake.Wget#14]
I was trying to use the tool, but I found that ArgumentCustomization doesn't exist inside `WgetSettings` 

![image](https://user-images.githubusercontent.com/26596347/115990390-ba736180-a5cb-11eb-8b7b-c219f36351af.png)

**Comment by badrshs** [comment]
I was checking the issue, and  I have to install ` Cake.Core.Tooling` to get that working,

**Comment by nils-a** [comment]
@badrshs Sorry to hear you are having issues. 

Are you trying to use this library "standalone"?
This library is an addin for [Cake](https://cakebuild.net/) and would normally be used in combination with one of the [Cake runners](https://cakebuild.net/docs/running-builds/runners/).

To answer the question
> `Wget(settings); <==== what is this  ?`

It's an extension on `ICakeContext`, defined in [`WgetRunnerAliases`](https://cakebuild.net/api/Cake.Wget/WgetRunnerAliases/).
So, in a Cake script it can be used "globally", as shown in the example and in Cake.Frosting it would be used like a method on the `context`. I.e. `this.context.Wget(settings)`.

A minimal working example for the .NET Tool runner would be:

```cakescript
#addin nuget:?package=Cake.Wget&version=1.1.0
var target = Argument("target", "Default");

Task("Default")
.Does(() => {
   Wget(new WgetSettings {
      Url = new Uri("https://wordpress.org/latest.zip"),
      ArgumentCustomization = args=>args.Append("--debug")
       .Append("--dns-timeout=10")
   });
});

RunTarget(target);
```

A minimal example for Cake.Frosting would be:

```cs
using System;
using Cake.Core;
using Cake.Frosting;
using Cake.Wget;

public static class Program
{
    public static int Main(string[] args)
    {
        return new CakeHost()
            .UseContext<BuildContext>()
            .Run(args);
    }
}

public class BuildContext : FrostingContext
{
    public BuildContext(ICakeContext context)
        : base(context)
    {
    }
}

[TaskName("Default")]
public class DefaultTask : FrostingTask
{
    public override void Run(ICakeContext context)
    {
        context.Wget(new WgetSettings {
            Url = new Uri("https://wordpress.org/latest.zip"),
            ArgumentCustomization = args=>args.Append("--debug")
                .Append("--dns-timeout=10")
        });
    }
}
```

Here, apart from the obvious reference to Cake.Frosting, only a reference to Cake.Wget is needed.
In both cases, no additional reference to Cake.Core is needed.

**Comment by deqenq** [comment]
@badrshs I could not explain it better than @nils-a . This is just add-in for Cake build and it is not intended to be used any other way.

**Comment by badrshs** [comment]
@nils-a thanks for the explanation. I was trying to install that with .net core project, didn't know it was just an add-in for another project 😅 sorry I didn't fully read the documentation. 

thanks for the help 🙌👍
